name: 'Mudlet Map Diff'
description: 'Generates diff of Mudlet map'
author: Delwing
branding:
  icon: check-square
  color: blue
inputs:
  old-map:
    description: 'Path to old map'
    required: true
  new-map:
    description: 'Path to new map if different'
    required: false
    default: ""
  github-token:
    description: 'Github Token'
    default: ${{ github.token }}
    required: false
  reuse-comment:
    description: 'Reuse comment'
    default: 'false'
    required: false
  collapse-diff:
    description: 'Collapse diff'
    default: 'false'
    required: false
  summary:
    description: 'Output diff to job summary'
    default: 'true'
    required: false
outputs:
  diff: 
    description: 'Diff JSON'
    value: ${{ steps.diff-step.outputs.diff }}
  markdown:
    description: 'Markdown report'
    value: ${{ steps.diff-step.outputs.markdown }}
runs:
  using: 'docker'
  image: 'Dockerfile'
