name: 'Mudlet Map Diff'
description: 'Generates diff of Mudlet map'
inputs:
  old-map:
    description: 'Path to old map'
    required: true
  new-map:
    description: 'Path to new map id different'
    required: false
  tmp-dir:
    description: 'Temporary directory for diff check'
    default: 'tmp'
    required: false
  github-token:
    description: 'Github Token'
    default: ${{ github.token }}
    required: false
outputs:
  diff: 
    description: 'Diff JSON'
    value: ${{steps.diff-step.outputs.diff}}
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{github.base_ref}}
        path: ${{inputs.tmp-dir}}
    - name: Diff
      id: diff-step
      uses: ./docker-action
      with:
        old-map: ${{inputs.old-map}}
        new-map: ${{inputs.new-map}}
        tmp-dir: ${{inputs.tmp-dir}}
        github-token: ${{inputs.github-token}}
    
