name: Create diff

on: [pull_request, workflow_dispatch]

jobs:
  map-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local code
        uses: actions/checkout@v4
      - name: Create DIFF
        id: diff
        uses: ./
        with:
          old-map: map_master3.dat
          reuse-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}