name: Test Action
on:
  pull_request:
    paths:
      - '**.dat'
      - 'action.yml'
      - '**.js'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Mudlet Map Diff
        uses: ./
        with:
          old-map: example/map.dat
          new-map: example/map.dat
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary: true
